name: Compare Providers Streaming

run-name: >-
  ${{ github.event_name == 'schedule' &&
    (github.event.schedule == '0 0 * * 1' && 'Scheduled: Static' ||
     github.event.schedule == '0 0 * * 2' && 'Scheduled: Trace-A Trace-B' ||
     github.event.schedule == '0 0 * * 3' && 'Scheduled: Multiturn-A Multiturn-B Multiturn-C' ||
     github.event.schedule == '0 0 * * 4' && 'Scheduled: Multiturn-NoCache-A Multiturn-NoCache-B Multiturn-NoCache-C' ||
     github.event.schedule == '0 0 * * 5' && 'Scheduled: VQA-A VQA-B' ||
     'Scheduled') ||
    format('Manual:{0}{1}{2}{3}{4}{5}{6}{7}{8}{9}{10}{11}',
      inputs.run_static && ' Static' || '',
      inputs.run_trace_a && ' Trace-A' || '',
      inputs.run_trace_b && ' Trace-B' || '',
      inputs.run_multiturn_a && ' Multiturn-A' || '',
      inputs.run_multiturn_b && ' Multiturn-B' || '',
      inputs.run_multiturn_c && ' Multiturn-C' || '',
      inputs.run_multiturn_nocache_a && ' Multiturn-NoCache-A' || '',
      inputs.run_multiturn_nocache_b && ' Multiturn-NoCache-B' || '',
      inputs.run_multiturn_nocache_c && ' Multiturn-NoCache-C' || '',
      inputs.run_vqa_a && ' VQA-A' || '',
      inputs.run_vqa_b && ' VQA-B' || '',
      inputs.run_vqa_v2 && ' VQA-V2' || '') }}

on:
  workflow_dispatch:
    inputs:
      run_static:
        description: 'Run Static Benchmark'
        type: boolean
        default: false
      run_trace_a:
        description: 'Run Trace Benchmark A'
        type: boolean
        default: false
      run_trace_b:
        description: 'Run Trace Benchmark B'
        type: boolean
        default: false
      run_multiturn_a:
        description: 'Run Multiturn Benchmark A'
        type: boolean
        default: false
      run_multiturn_b:
        description: 'Run Multiturn Benchmark B'
        type: boolean
        default: false
      run_multiturn_c:
        description: 'Run Multiturn Benchmark C'
        type: boolean
        default: false
      run_vqa_a:
        description: 'Run VQA Benchmark A'
        type: boolean
        default: false
      run_vqa_b:
        description: 'Run VQA Benchmark B'
        type: boolean
        default: false
      run_vqa_v2:
        description: 'Run VQA Benchmark V2'
        type: boolean
        default: false
      run_multiturn_nocache_a:
        description: 'Run Multiturn No-Cache Benchmark A'
        type: boolean
        default: false
      run_multiturn_nocache_b:
        description: 'Run Multiturn No-Cache Benchmark B'
        type: boolean
        default: false
      run_multiturn_nocache_c:
        description: 'Run Multiturn No-Cache Benchmark C'
        type: boolean
        default: false
  # schedule:
  #   # Monday (Static)
  #   - cron: "0 0 * * 1"
  #   # Tuesday (Trace A + B)
  #   - cron: "0 0 * * 2"
  #   # Wednesday (Multiturn A + B + C)
  #   - cron: "0 0 * * 3"
  #   # Thursday (Multiturn No-Cache A + B + C)
  #   - cron: "0 0 * * 4"
  #   # Friday (VQA A + B)
  #   - cron: "0 0 * * 5"

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_AI_TOKEN: ${{ secrets.CLOUDFLARE_AI_TOKEN }}
  GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
  GOOGLE_CLOUD_LOCATION: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
  LLAMA_4_GOOGLE_CLOUD_LOCATION: ${{ secrets.LLAMA_4_GOOGLE_CLOUD_LOCATION }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  HYPERBOLIC_API: ${{ secrets.HYPERBOLIC_API }}
  OPEN_AI_API: ${{ secrets.OPEN_AI_API }}
  PERPLEXITY_AI_API: ${{ secrets.PERPLEXITY_AI_API }}
  TOGETHER_AI_API: ${{ secrets.TOGETHER_AI_API }}
  ANTHROPIC_API: ${{ secrets.ANTHROPIC_API }}
  AWS_BEDROCK_ACCESS_KEY_ID: ${{ secrets.AWS_BEDROCK_ACCESS_KEY_ID }}
  AWS_BEDROCK_SECRET_ACCESS_KEY: ${{ secrets.AWS_BEDROCK_SECRET_ACCESS_KEY }}
  AWS_BEDROCK_REGION: ${{ secrets.AWS_BEDROCK_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AZURE_AI_ENDPOINT: ${{ secrets.AZURE_AI_ENDPOINT }}
  AZURE_AI_API_KEY: ${{ secrets.AZURE_AI_API_KEY }}
  AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}

jobs:
  static-benchmark:
    name: Static Benchmark
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_static == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 1') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Experiment
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming.json

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-static
        path: ${{ github.workspace }}/benchmark_graph

  trace-benchmark-a:
    name: Trace Benchmark A
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_trace_a == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 2') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Trace Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "trace_conv.json"
        echo "TRACE_DATASET_PATH=${{ github.workspace }}/trace_conv.json" >> $GITHUB_ENV

    - name: Run Trace Experiment A
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_trace_A.json

    - name: Upload Trace Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-trace-a
        path: |
          ${{ github.workspace }}/trace/proxy/*.log
          ${{ github.workspace }}/trace/*.result
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-trace-a
        path: ${{ github.workspace }}/benchmark_graph

  trace-benchmark-b:
    name: Trace Benchmark B
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_trace_b == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 2') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Trace Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "trace_conv.json"
        echo "TRACE_DATASET_PATH=${{ github.workspace }}/trace_conv.json" >> $GITHUB_ENV

    - name: Run Trace Experiment B
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_trace_B.json

    - name: Upload Trace Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-trace-b
        path: |
          ${{ github.workspace }}/trace/proxy/*.log
          ${{ github.workspace }}/trace/*.result
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-trace-b
        path: ${{ github.workspace }}/benchmark_graph

  multiturn-benchmark-a:
    name: Multiturn Benchmark A
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_multiturn_a == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 3') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Multiturn Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "multiturn.json"
        echo "MULTITURN_DATASET_PATH=${{ github.workspace }}/multiturn.json" >> $GITHUB_ENV

    - name: Run Multiturn Experiment A
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_multiturn_A.json

    - name: Upload Multiturn Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-multiturn-a
        path: |
          ${{ github.workspace }}/multiturn/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-multiturn-a
        path: ${{ github.workspace }}/benchmark_graph

  multiturn-benchmark-b:
    name: Multiturn Benchmark B
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_multiturn_b == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 3') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Multiturn Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "multiturn.json"
        echo "MULTITURN_DATASET_PATH=${{ github.workspace }}/multiturn.json" >> $GITHUB_ENV

    - name: Run Multiturn Experiment B
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_multiturn_B.json

    - name: Upload Multiturn Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-multiturn-b
        path: |
          ${{ github.workspace }}/multiturn/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-multiturn-b
        path: ${{ github.workspace }}/benchmark_graph

  multiturn-benchmark-c:
    name: Multiturn Benchmark C
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_multiturn_c == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 3') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Multiturn Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "multiturn.json"
        echo "MULTITURN_DATASET_PATH=${{ github.workspace }}/multiturn.json" >> $GITHUB_ENV

    - name: Run Multiturn Experiment C
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_multiturn_C.json

    - name: Upload Multiturn Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-multiturn-c
        path: |
          ${{ github.workspace }}/multiturn/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-multiturn-c
        path: ${{ github.workspace }}/benchmark_graph

  vqa-benchmark-a:
    name: VQA Benchmark A
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_vqa_a == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 5') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup VQA Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "vqa_dataset.tar.gz"
        tar -xzf vqa_dataset.tar.gz
        mv vqa_dataset/vqa.jsonl .
        mv vqa_dataset/val2014 .
        rm -rf vqa_dataset vqa_dataset.tar.gz
        echo "VQA_DATASET_PATH=${{ github.workspace }}/vqa.jsonl" >> $GITHUB_ENV

    - name: Run VQA Experiment A
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_vqa_A.json

    - name: Upload VQA Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-vqa-a
        path: |
          ${{ github.workspace }}/vqa/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-vqa-a
        path: ${{ github.workspace }}/benchmark_graph

  vqa-benchmark-b:
    name: VQA Benchmark B
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_vqa_b == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 5') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup VQA Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "vqa_dataset.tar.gz"
        tar -xzf vqa_dataset.tar.gz
        mv vqa_dataset/vqa.jsonl .
        mv vqa_dataset/val2014 .
        rm -rf vqa_dataset vqa_dataset.tar.gz
        echo "VQA_DATASET_PATH=${{ github.workspace }}/vqa.jsonl" >> $GITHUB_ENV

    - name: Run VQA Experiment B
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_vqa_B.json

    - name: Upload VQA Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-vqa-b
        path: |
          ${{ github.workspace }}/vqa/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-vqa-b
        path: ${{ github.workspace }}/benchmark_graph

  multiturn-nocache-benchmark-a:
    name: Multiturn No-Cache Benchmark A
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_multiturn_nocache_a == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 4') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Multiturn No-Cache Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "multiturn_no_cache.json"
        echo "MULTITURN_DATASET_PATH=${{ github.workspace }}/multiturn_no_cache.json" >> $GITHUB_ENV

    - name: Run Multiturn No-Cache Experiment A
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_multiturn_nocache_A.json

    - name: Upload Multiturn No-Cache Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-multiturn-nocache-a
        path: |
          ${{ github.workspace }}/multiturn/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-multiturn-nocache-a
        path: ${{ github.workspace }}/benchmark_graph

  multiturn-nocache-benchmark-b:
    name: Multiturn No-Cache Benchmark B
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_multiturn_nocache_b == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 4') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Multiturn No-Cache Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "multiturn_no_cache.json"
        echo "MULTITURN_DATASET_PATH=${{ github.workspace }}/multiturn_no_cache.json" >> $GITHUB_ENV

    - name: Run Multiturn No-Cache Experiment B
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_multiturn_nocache_B.json

    - name: Upload Multiturn No-Cache Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-multiturn-nocache-b
        path: |
          ${{ github.workspace }}/multiturn/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-multiturn-nocache-b
        path: ${{ github.workspace }}/benchmark_graph

  multiturn-nocache-benchmark-c:
    name: Multiturn No-Cache Benchmark C
    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.run_multiturn_nocache_c == true) || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * 4') }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Multiturn No-Cache Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "multiturn_no_cache.json"
        echo "MULTITURN_DATASET_PATH=${{ github.workspace }}/multiturn_no_cache.json" >> $GITHUB_ENV

    - name: Run Multiturn No-Cache Experiment C
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_multiturn_nocache_C.json

    - name: Upload Multiturn No-Cache Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-multiturn-nocache-c
        path: |
          ${{ github.workspace }}/multiturn/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-multiturn-nocache-c
        path: ${{ github.workspace }}/benchmark_graph

  vqa-benchmark-v2:
    name: VQA Benchmark V2
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_vqa_v2 == true }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup VQA Input
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download -p "vqa_dataset.tar.gz"
        tar -xzf vqa_dataset.tar.gz
        mv vqa_dataset/vqa.jsonl .
        mv vqa_dataset/val2014 .
        rm -rf vqa_dataset vqa_dataset.tar.gz
        echo "VQA_DATASET_PATH=${{ github.workspace }}/vqa.jsonl" >> $GITHUB_ENV

    - name: Run VQA Experiment V2
      run: python -u main.py -c benchmarking/experiments/compare_providers_streaming_vqa_v2.json

    - name: Upload VQA Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-vqa-v2
        path: |
          ${{ github.workspace }}/vqa/logs/*.csv
        if-no-files-found: warn

    - name: Upload Experiment Outputs
      uses: actions/upload-artifact@v4
      with:
        name: results-vqa-v2
        path: ${{ github.workspace }}/benchmark_graph

  download-artifacts:
    runs-on: ubuntu-latest
    needs: [static-benchmark, trace-benchmark-a, trace-benchmark-b, multiturn-benchmark-a, multiturn-benchmark-b, multiturn-benchmark-c, multiturn-nocache-benchmark-a, multiturn-nocache-benchmark-b, multiturn-nocache-benchmark-c, vqa-benchmark-a, vqa-benchmark-b, vqa-benchmark-v2]

    # Run if at least one of the previous jobs succeed
    if: always() && (needs.static-benchmark.result == 'success' || needs.trace-benchmark-a.result == 'success' || needs.trace-benchmark-b.result == 'success' || needs.multiturn-benchmark-a.result == 'success' || needs.multiturn-benchmark-b.result == 'success' || needs.multiturn-benchmark-c.result == 'success' || needs.multiturn-nocache-benchmark-a.result == 'success' || needs.multiturn-nocache-benchmark-b.result == 'success' || needs.multiturn-nocache-benchmark-c.result == 'success' || needs.vqa-benchmark-a.result == 'success' || needs.vqa-benchmark-b.result == 'success' || needs.vqa-benchmark-v2.result == 'success')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List Downloaded Artifacts
        run: ls -R artifacts
